 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import ConexaoBD.Dados;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Silvio da Silva
 * Classe para a janela de dados 
 */
public class NewJInternalFrameConsultaPessoas extends javax.swing.JInternalFrame {
Dados dadosArq = new Dados();

        
    
    
    /**
     * Creates new form NewJInternalFrameConsultaPessoas
     */
    public NewJInternalFrameConsultaPessoas() {
        initComponents();
        
        DefaultTableModel ConsultaPessoas = (DefaultTableModel) jTableConsultaPessoasPrimeiraEtapa.getModel();
        jTableConsultaPessoasPrimeiraEtapa.setRowSorter(new TableRowSorter(ConsultaPessoas));
        String Caminho="Pessoas.dad";
        String conteudo="";
           try{
           FileReader arq = new FileReader(Caminho);
           BufferedReader lerArq = new BufferedReader(arq);
           String linha="";
           
           try{
               linha = lerArq.readLine();
               while(linha!=null){
                   String[] coluna = linha.split(";");
                   conteudo += linha;
                   linha = lerArq.readLine();
                   Object [] posicao = {coluna[1],coluna[0],coluna[2],coluna[3]};
                   ConsultaPessoas.addRow(posicao);
                }
               arq.close();
           } catch (IOException ex) {
               conteudo = "Erro: Nao foi possivel ler Arquivo ! ";
           }
       } catch(IOException ex) {
           conteudo = "Erro: Arquivo inexistente ! ";
       }
        if (conteudo.contains("Erro"));            
        else {
            }
    
    
    
    
    
    
    
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultaPessoasPrimeiraEtapa = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableConsultaEtapas = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Consulta Pessoas com Salas");
        setPreferredSize(new java.awt.Dimension(400, 188));

        jTableConsultaPessoasPrimeiraEtapa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableConsultaPessoasPrimeiraEtapa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sala", "Nome", "Sala Cafe", "Etapas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableConsultaPessoasPrimeiraEtapa.getTableHeader().setReorderingAllowed(false);
        jTableConsultaPessoasPrimeiraEtapa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableConsultaPessoasPrimeiraEtapaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableConsultaPessoasPrimeiraEtapa);

        jTableConsultaEtapas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTableConsultaEtapas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Etapa", "Sala", "Sala Cafe"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableConsultaEtapas);

        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonAtualizar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(400, 10, 591, 482);
    }// </editor-fold>//GEN-END:initComponents

    private void jTableConsultaPessoasPrimeiraEtapaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableConsultaPessoasPrimeiraEtapaMouseClicked
        // Selecionar itens para a tabela das etapas
        DefaultTableModel ConsultaEtapas = (DefaultTableModel) jTableConsultaEtapas.getModel();
        
        String nome =""+jTableConsultaPessoasPrimeiraEtapa.getValueAt(jTableConsultaPessoasPrimeiraEtapa.getSelectedRow(),1);
        ConsultaEtapas.setRowCount(0);
        String Caminho="Pessoas.dad";
        String conteudo="";
           try{
           FileReader arq = new FileReader(Caminho);
           BufferedReader lerArq = new BufferedReader(arq);
           String linha="";
           
           try{
               linha = lerArq.readLine();
               while(linha!=null){ 
                   String[] coluna = linha.split(";");
                   conteudo += linha;
                   linha = lerArq.readLine();
                   Object [] posicao = {coluna[3],coluna[1],coluna[2],};
                   if (coluna[0].contains(nome)){
                   ConsultaEtapas.addRow(posicao);
               }else { }
               }arq.close();
           } catch (IOException ex) {
               conteudo = "Erro: Nao foi possivel ler Arquivo ! ";
           }
       } catch(IOException ex) {
           conteudo = "Erro: Arquivo inexistente ! ";
       }
        if (conteudo.contains("Erro"));            
        else {
            }
    
    }//GEN-LAST:event_jTableConsultaPessoasPrimeiraEtapaMouseClicked

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        DefaultTableModel ConsultaPessoas = (DefaultTableModel) jTableConsultaPessoasPrimeiraEtapa.getModel();
        DefaultTableModel ConsultaEtapas = (DefaultTableModel) jTableConsultaEtapas.getModel();
        ConsultaPessoas.setRowCount(0);
        ConsultaEtapas.setRowCount(0);
        jTableConsultaPessoasPrimeiraEtapa.setRowSorter(new TableRowSorter(ConsultaPessoas));
        String Caminho="Pessoas.dad";
        String conteudo="";
           try{
           FileReader arq = new FileReader(Caminho);
           BufferedReader lerArq = new BufferedReader(arq);
           String linha="";
           
           try{
               linha = lerArq.readLine();
               while(linha!=null){
                   String[] coluna = linha.split(";");
                   conteudo += linha;
                   linha = lerArq.readLine();
                   Object [] posicao = {coluna[1],coluna[0],coluna[2],coluna[3]};
                   ConsultaPessoas.addRow(posicao);
                }
               arq.close();
           } catch (IOException ex) {
               conteudo = "Erro: Nao foi possivel ler Arquivo ! ";
           }
       } catch(IOException ex) {
           conteudo = "Erro: Arquivo inexistente ! ";
       }
        if (conteudo.contains("Erro"));            
        else {
            }
    
    }//GEN-LAST:event_jButtonAtualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableConsultaEtapas;
    private javax.swing.JTable jTableConsultaPessoasPrimeiraEtapa;
    // End of variables declaration//GEN-END:variables
}
