/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import ConexaoBD.Dados;
import ModeloDeclare.DecCadSala;
import modeloFuncoes.FuncSalas;

/**
 *
 * @author Silvio da Silva
 * Classe para a janela de dados 
 */
public class NewJInternalFrameCadSala extends javax.swing.JInternalFrame {
    FuncSalas sala = new FuncSalas();
    DecCadSala cadSala = new DecCadSala();
    Dados Banco = new Dados();
    
        

    /**
     * Creates new form NewJInternalFrameCadSala
     */
    public NewJInternalFrameCadSala() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNomeSala = new javax.swing.JLabel();
        jLabelCapSala = new javax.swing.JLabel();
        jTextFieldNomeSala = new javax.swing.JTextField();
        jTextFieldCapSala = new javax.swing.JTextField();
        jButtonSalvarSala = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastros de Salas");

        jLabelNomeSala.setText("Nome da sala:");

        jLabelCapSala.setText("Capacidade:");

        jButtonSalvarSala.setText("Salvar");
        jButtonSalvarSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarSalaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNomeSala)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonSalvarSala))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCapSala)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCapSala, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeSala)
                    .addComponent(jTextFieldNomeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCapSala)
                    .addComponent(jTextFieldCapSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonSalvarSala)
                .addContainerGap())
        );

        setBounds(400, 75, 400, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarSalaActionPerformed
        cadSala.setNomeSala(jTextFieldNomeSala.getText());
        cadSala.setCapacidadeSala(Integer.parseInt(jTextFieldCapSala.getText()));
        String Caminho="Sala.dad";
        String Dados=cadSala.getNomeSala();
        String Dados2=String.valueOf(cadSala.getCapacidadeSala());
        String conteudo = Dados+";"+Dados2;
        Banco.Gravar(Caminho,conteudo);
        jTextFieldNomeSala.setText("");
        jTextFieldCapSala.setText("");
        jTextFieldNomeSala.requestFocus(true);
    }//GEN-LAST:event_jButtonSalvarSalaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarSala;
    private javax.swing.JLabel jLabelCapSala;
    private javax.swing.JLabel jLabelNomeSala;
    private javax.swing.JTextField jTextFieldCapSala;
    private javax.swing.JTextField jTextFieldNomeSala;
    // End of variables declaration//GEN-END:variables
}
