/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import ConexaoBD.Dados;
import ModeloDeclare.DecCadCafe;
import modeloFuncoes.FuncCafe;

/**
 *
 * @author Silvio da Silva
 * Classe para a janela de dados 
 */
public class NewJInternalFrameCafe extends javax.swing.JInternalFrame {
    FuncCafe fc = new FuncCafe();
    DecCadCafe cadCafe = new DecCadCafe();
    Dados Banco = new Dados();
    
    
    
    

    /**
     * Creates new form NewJInternalFrameCafe
     */
    public NewJInternalFrameCafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jTextFieldCapCafe = new javax.swing.JTextField();
        jTextFieldNomeSalaCafe = new javax.swing.JTextField();
        jLabelCadEspCafe2 = new javax.swing.JLabel();
        jButtonSalvarCafe2 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Espaços de Café");
        setToolTipText("");

        jLabel4.setText("Capacidade :");

        jLabelCadEspCafe2.setText("Nome Espaço Café:");

        jButtonSalvarCafe2.setText("Salvar");
        jButtonSalvarCafe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarCafe2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonSalvarCafe2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadEspCafe2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCapCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeSalaCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 52, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCadEspCafe2)
                    .addComponent(jTextFieldNomeSalaCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldCapCafe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jButtonSalvarCafe2)
                .addContainerGap())
        );

        setBounds(400, 75, 400, 184);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarCafe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarCafe2ActionPerformed
      
        cadCafe.setNomeSalaCafe(jTextFieldNomeSalaCafe.getText());
        cadCafe.setCapacidadeCafe(Integer.parseInt(jTextFieldCapCafe.getText()));
        String Caminho="SalaCafe.dad";
        String Dados=cadCafe.getNomeSalaCafe();
        String Dados2=String.valueOf(cadCafe.getCapacidadeCafe());
        String conteudo = Dados+";"+Dados2;
        Banco.Gravar(Caminho,conteudo);
        jTextFieldNomeSalaCafe.setText("");
        jTextFieldCapCafe.setText("");
        jTextFieldNomeSalaCafe.requestFocus(true);
        
        
        
        
        
    }//GEN-LAST:event_jButtonSalvarCafe2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSalvarCafe2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCadEspCafe2;
    private javax.swing.JTextField jTextFieldCapCafe;
    private javax.swing.JTextField jTextFieldNomeSalaCafe;
    // End of variables declaration//GEN-END:variables
}
