  /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import modeloFuncoes.FuncSalas;
/**
 *
 * @author Silvio da Silva
 * Janela princinpal que acionar as internas 
 * 
 */
public class TelaInicial extends javax.swing.JFrame {
    FuncSalas fSala = new FuncSalas();
    NewJInternalFrameCadPessoas telaPes = new NewJInternalFrameCadPessoas();
    NewJInternalFrameCadSala telaSala = new NewJInternalFrameCadSala();
    NewJInternalFrameCafe telaCafe = new NewJInternalFrameCafe();
    NewJInternalFrameConsultaPessoas telaConPes = new NewJInternalFrameConsultaPessoas();
    NewJInternalFrameConsultaSalas telaConSala = new NewJInternalFrameConsultaSalas();
    
    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelMenu = new javax.swing.JLabel();
        jButtonCadPessoas = new javax.swing.JButton();
        jButtonCadSalas = new javax.swing.JButton();
        jButtonCadCafe = new javax.swing.JButton();
        jButtonConPessoas = new javax.swing.JButton();
        jButtonConSalas = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelFundoTelaInicial = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelTitulo.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("Controle de Treinamentos");
        jLabelTitulo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabelTitulo);
        jLabelTitulo.setBounds(40, 20, 280, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenu.setText("Menu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButtonCadPessoas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadPessoas.setText("Cadastro de Pessoas ");
        jButtonCadPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPessoasActionPerformed(evt);
            }
        });

        jButtonCadSalas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadSalas.setText("Cadastro de Salas");
        jButtonCadSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadSalasActionPerformed(evt);
            }
        });

        jButtonCadCafe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCadCafe.setText("Cadastro de Espaço de Café");
        jButtonCadCafe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadCafeActionPerformed(evt);
            }
        });

        jButtonConPessoas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConPessoas.setText("Consulta Pessoas");
        jButtonConPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConPessoasActionPerformed(evt);
            }
        });

        jButtonConSalas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonConSalas.setText("Consulta Salas");
        jButtonConSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConSalasActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCadPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCadCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jButtonSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCadSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jButtonCadCafe, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConPessoas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonConSalas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(40, 70, 280, 380);

        jLabelFundoTelaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoTelaInicial);
        jLabelFundoTelaInicial.setBounds(-9, -5, 1050, 510);

        setSize(new java.awt.Dimension(1047, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPessoasActionPerformed
        jLabelFundoTelaInicial.add(telaPes);
        telaPes.setVisible(true);
        telaSala.dispose();
        telaCafe.dispose();
        telaConPes.dispose();
        telaConSala.dispose();
        
    }//GEN-LAST:event_jButtonCadPessoasActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonCadSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadSalasActionPerformed
        jLabelFundoTelaInicial.add(telaSala);
        telaSala.setVisible(true);
        telaCafe.dispose();
        telaPes.dispose();
        telaConPes.dispose();
        telaConSala.dispose();
    }//GEN-LAST:event_jButtonCadSalasActionPerformed

    private void jButtonCadCafeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadCafeActionPerformed
        jLabelFundoTelaInicial.add(telaCafe);
        telaCafe.setVisible(true);
        telaPes.dispose();
        telaSala.dispose();
        telaConPes.dispose();
        telaConSala.dispose();
        
    }//GEN-LAST:event_jButtonCadCafeActionPerformed

    private void jButtonConPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConPessoasActionPerformed
        jLabelFundoTelaInicial.add(telaConPes);
        telaConPes.setVisible(true);
        telaPes.dispose();
        telaSala.dispose();
        telaCafe.dispose();
        telaConSala.dispose();
        
    }//GEN-LAST:event_jButtonConPessoasActionPerformed

    private void jButtonConSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConSalasActionPerformed
        jLabelFundoTelaInicial.add(telaConSala);
        telaConSala.setVisible(true);
        telaPes.dispose();
        telaSala.dispose();
        telaCafe.dispose();
        telaConPes.dispose();
    }//GEN-LAST:event_jButtonConSalasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadCafe;
    private javax.swing.JButton jButtonCadPessoas;
    private javax.swing.JButton jButtonCadSalas;
    private javax.swing.JButton jButtonConPessoas;
    private javax.swing.JButton jButtonConSalas;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JLabel jLabelFundoTelaInicial;
    private javax.swing.JLabel jLabelMenu;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
